# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: casper-java-sdk

on:
  push:
    branches: [ workflow-tests ]
  pull_request:
    branches: [ workflow-tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate jacoco Code Coverage with Gradle
      run: ./gradlew jacocoTestReport
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.4.1

